#!/bin/sh
#
# Setup script for AnsibleLaptop
# This will only ensure that Ansible is installed and working.
#

REPO_NAME=AnsibleLaptop
REPO_URL=https://github.com/ksylvan/${REPO_NAME}

myUser=${USER}

exists()
{
  command -v "$1"
}

sudoersSetup()
{
  sudoersFile=/etc/sudoers.d/${myUser}
  tmpFile=/tmp/x$$
  echo "${myUser} ALL=(ALL) NOPASSWD: ALL" > ${tmpFile}
  sudo cp ${tmpFile} ${sudoersFile}
  if [ $? -eq 0 ]; then
    echo "User ${myUser} can now sudo without password."
    sudo rm -f ${tmpFile}
  else
    echo "ERROR: Need elevated permissions for user ${myUser}. Exiting."
    exit $?
  fi
}

ansibleCanSudo()
{
  if sudo -n id -u > /dev/null 2>&1; then
    echo "User ${myUser} can already sudo without password. Skipping setup."
  else
    sudoersSetup
  fi
}

ansibleInstall()
{
  if [ -z "$(exists ansible)" ]; then
    sudo dnf -y install ansible python2-dnf libselinux-python
  else
    echo "WARNING: Ansible is already installed. Skipping install."
  fi
}

ansibleTest()
{
  if ansible laptop -m ping; then
    echo "SUCCESS: Ansible is working correctly against localhost."
  else
    echo "ERROR: Something is wrong with your setup."
  fi
}

ansibleCanSudo
ansibleInstall
ansibleTest

cd $(dirname $0)/..
ansible-galaxy install -p roles -r requirements.yml

echo "Set up a group_vars/all file as outlined in ${REPO_URL}"
echo ""
echo "Once everything is set up, run ansible-playbook:"
echo ""
echo "    ansible-playbook site.yml"
echo ""
echo "Reboot when that completes."
