#!/bin/sh
#
# Setup script for AnsibleLaptop
# This will only ensure that Ansible is installed and working.
#
cd $(dirname $0)/..

exists()
{
  command -v "$1"
}

sudoersSetup()
{
  sudoersFile=/etc/sudoers.d/ansible
  tmpFile=/tmp/x$$
  if sudo -n cp /dev/null ${tmpFile} > /dev/null 2>&1; then
    echo "User ansible can already sudo without password. Skipping setup."
  else
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' > ${tmpFile}
    sudo cp ${tmpFile} ${sudoersFile}
    echo "User ansible can now sudo without password."
  fi
  sudo rm -f ${tmpFile}
}

ansibleInstall()
{
  if [ -z "$(exists ansible)" ]; then
    sudo dnf -y install ansible
  else
    echo "WARNING: Ansible is already installed. Skipping install."
  fi
}

ansibleTest()
{
  if ansible laptop -m ping; then
    echo "SUCCESS: Ansible is working correctly against localhost."
  else
    echo "ERROR: Something is wrong with your setup."
  fi
}

sudoersSetup
ansibleInstall
ansibleTest
