#!/bin/sh
#
# Setup script for AnsibleLaptop
# This will only ensure that Ansible is installed and working.
#

REPO_NAME=AnsibleLaptop
REPO_URL=https://github.com/ksylvan/${REPO_NAME}
ANSIBLE_LAPTOP_CONF_DIR=${HOME}/.ansible_laptop

myUser=${USER}

exists()
{
  command -v "$1"
}

sudoersSetup()
{
  sudoersFile=/etc/sudoers.d/${myUser}
  tmpFile=/tmp/x$$
  echo "${myUser} ALL=(ALL) NOPASSWD: ALL" > ${tmpFile}
  sudo cp ${tmpFile} ${sudoersFile}
  if [ $? -eq 0 ]; then
    echo "User ${myUser} can now sudo without password."
    sudo rm -f ${tmpFile}
  else
    echo "ERROR: Need elevated permissions for user ${myUser}. Exiting."
    exit $?
  fi
}

ansibleCanSudo()
{
  if sudo -n id -u > /dev/null 2>&1; then
    echo "User ${myUser} can already sudo without password. Skipping setup."
  else
    sudoersSetup
  fi
}

ansibleInstall()
{
  if [ -z "$(exists ansible)" ]; then
    sudo dnf -y install ansible python2-dnf libselinux-python
  else
    echo "WARNING: Ansible is already installed. Skipping install."
  fi
}

ansibleVariables()
{
  VARS_FILE=${ANSIBLE_LAPTOP_CONF_DIR}/setup.yml
  if [ -r ${VARS_FILE} ]; then
    echo ""
    echo "Variables file ${VARS_FILE} already exists. Skipping."
  else
    if [ ! -d ${ANSIBLE_LAPTOP_CONF_DIR} ]; then
      mkdir -p ${ANSIBLE_LAPTOP_CONF_DIR}
    fi
    echo ""
    cp bootstrap/variables.yml ${VARS_FILE}
    echo ""
    echo "New variables file ${VARS_FILE} set up."
  fi
  echo "Edit the variables file and then run ansible-playbook:"
  echo ""
  echo "    make"
  echo ""
}

cd $(dirname $0)/..

ansibleCanSudo
ansibleInstall
make test
ansibleVariables
