# Makefile for convenience
#

.PHONY: all deploy galaxy setup test

DEBUG=
LOCAL=$(HOME)/.ansible_laptop/local.yml
LOCAL_PLAYBOOK=./.local.yml

all: galaxy deploy
	@echo '---' > $(LOCAL_PLAYBOOK)
	@echo '# autogenerated by Makefile' >> $(LOCAL_PLAYBOOK)
	@if [ -r $(LOCAL) ]; then \
		echo '- include: ' $(LOCAL) >> $(LOCAL_PLAYBOOK); \
	else \
		echo '- hosts: laptop' >> $(LOCAL_PLAYBOOK); \
		echo '  gather_facts: no' >> $(LOCAL_PLAYBOOK); \
	fi
	@ansible-playbook $(DEBUG) site.yml

galaxy: requirements.yml
	@ansible-galaxy install -p roles -r requirements.yml

setup:
	@./bootstrap/setup

test:
	@if ansible laptop -m ping; then \
		echo "SUCCESS: Ansible is working correctly against localhost."; \
	else \
		echo "ERROR: Something is wrong with your setup."; \
	fi
