#!/bin/sh
#

REPO_NAME=AnsibleLaptop
REPO_URL=https://github.com/ksylvan/${REPO_NAME}

if [ ! -d ${REPO_NAME} ]; then
  echo "Setting up the ${REPO_NAME} repository..."
  cd ${HOME}
  git clone ${REPO_URL}
  cd ${REPO_NAME}
else
  echo "${REPO_NAME} repository already exists."
  cd ${REPO_NAME}
  git pull
fi
echo ""
echo "Change directory to ${REPO_NAME} and run ./setup"
