#!/bin/sh
#
# Setup script for AnsibleLaptop
# This will only ensure that Ansible is installed and working.
#
exists()
{
  command -v "$1"
}

sudoersSetup()
{
  sudoersFile=/etc/sudoers.d/ansible
  tmpFile=/tmp/x$$
  if [ ! -r ${sudoersFile} ]; then
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' > ${tmpFile}
    sudo cp ${tmpFile} ${sudoersFile}; rm -f ${tmpFile}
    echo "User ansible can now sudo without password."
  else
    echo "The ${sudoersFile} is already set up. Skipping."
  fi
}

ansibleInstall()
{
  if [ -z "$(exists ansible)" ]; then
    sudo dnf -y install ansible
  else
    echo "WARNING: Ansible is already installed. Skipping install."
  fi
}

ansibleTest()
{
  if ansible all -i localhost, -c local -m ping; then
    echo "SUCCESS: Ansible is working correctly against localhost."
  else
    echo "ERROR: Something is wrong with your setup."
  fi
}

sudoersSetup
ansibleInstall
ansibleTest
