#!/bin/sh
#

dockerInstall()
{
  # Extracted from https://docs.docker.com/engine/installation/linux/fedora/
  #
  sudo dnf -y update
  curl -fsSL https://get.docker.com/ | sh
  sudo usermod -aG docker ${USER}
  sudo dnf -y install docker-engine
  sudo systemctl start docker
  sudo systemctl enable docker
}

sshSetup()
{
  cd ${HOME}
  if [ ! -d .ssh ]; then mkdir .ssh; fi
  chcon -R -t user_ssh_home_t ~/.ssh
  if [ ! -r .ssh/id_rsa ]; then
    ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  fi
}

ansibleTest()
{
  sudo dnf -y install python
  IMAGE=kayvan/ansible:2.1.0
  sudo docker run -v ${HOME}/.ssh:/root/.ssh --rm ${IMAGE} \
    ansible all -i 172.17.0.1, -m ping
}

dockerInstall
sshSetup
ansibleTest
