#!/bin/sh
#


dockerInstall()
{
  # Extracted from https://docs.docker.com/engine/installation/linux/fedora/
  #
  YUM_CFG=/etc/yum.repos.d/docker.repo

  if [ ! -r ${YUM_CFG} ]; then
    sudo tee ${YUM_CFG} <<-'EOF'
    [dockerrepo]
    name=Docker Repository
    baseurl=https://yum.dockerproject.org/repo/main/fedora/$releasever/
    enabled=1
    gpgcheck=1
    gpgkey=https://yum.dockerproject.org/gpg
EOF

    sudo dnf -y install docker-engine
    sudo systemctl start docker
  fi
}

sshSetup()
{
  cd ${HOME}
  if [ ! -d .ssh ]; then mkdir .ssh; fi
  chcon -R -t user_ssh_home_t ~/.ssh
  if [ ! -r .ssh/id_rsa ]; then
    ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  fi
}

ansibleTest()
{
  IMAGE=kayvan/ansible:2.1.0
  docker run -v /home/ksylvan/.ssh:/root/.ssh --rm -it ${IMAGE} \
    ansible all -i 172.17.0.1, -m ping
}

dockerInstall
sshSetup
ansibleTest
